apiVersion: v1
kind: Service
metadata:
  name: zenwebapi11-service
  labels:
    app: zenwebapi11
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
  selector:
    app: zenwebapi11
